platform :ios, '10.0'

target "FBSearch" do
    use_frameworks!
    
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    
    pod 'AFDateHelper', '~> 4.1'
    pod 'AlamofireImage', '~> 3.2'
    pod 'SDWebImage', '~> 4.0'
	pod 'Alamofire', '~> 4.4'
	pod 'SwiftyJSON'
	pod 'SwiftSpinner'
	pod 'EasyToast'
end
